### ISSUE TITLE
[PE-D][Tester D] Inaccurate Developer Guide naming

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-1/tp#186] opened 2024-11-08 15:11 UTC
![Screenshot 2024-11-08 at 4.12.55 PM.png](https://raw.githubusercontent.com/oolongwater/ped/main/files/dd9be985-c2a6-4f32-8ded-a4a753e9f235.png)

The DG does not reflect the name of the product. Perhaps change all "AddressBook" references to "ClubConnect"

-------------
Labels: `type.DocumentationBug` `severity.High`
original: oolongwater/ped#1

**Comment by limyixiang** [comment] 2024-11-11 08:55
I won't be fixing this. This is not a bug... The class name is `AddressBook` in our code, and so there is nothing wrong with these diagrams.

**Closed** 2024-11-11 08:56 UTC
Labels: can-delete
